"""drop default constraint for public_id

Revision ID: 44e85e0f2ce8
Revises: 71ab73abc607
Create Date: 2026-02-24 11:31:25.366174

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44e85e0f2ce8"
down_revision: str | Sequence[str] | None = "71ab73abc607"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("organizations", "public_id", server_default=None)
    op.alter_column("users", "public_id", server_default=None)
    op.alter_column("memberships", "public_id", server_default=None)
    op.alter_column("projects", "public_id", server_default=None)
    op.alter_column("tasks", "public_id", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("organizations", "public_id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("users", "public_id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("memberships", "public_id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("projects", "public_id", server_default=sa.text("gen_random_uuid()"))
    op.alter_column("tasks", "public_id", server_default=sa.text("gen_random_uuid()"))
    # ### end Alembic commands ###
