"""add org check constraint

Revision ID: b629fc290054
Revises: 6de5d1104d20
Create Date: 2026-03-16 21:21:06.085616

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "b629fc290054"
down_revision: str | Sequence[str] | None = "6de5d1104d20"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
