from typing import Protocol

from pet.domain.models import Organization, User


class OrganizationsRepo(Protocol):
    async def create(self, org: Organization) -> None: ...


class UsersRepo(Protocol):
    async def create(self, user: User) -> User | None: ...
    async def upsert(self, user: User) -> User: ...
    async def get_by_auth_identity(self, issuer: str, subject: str) -> User | None: ...
